# Generated by Django 5.0.7 on 2024-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposit_date',
            new_name='initial_deposite_date',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=10),
        ),
    ]
